spring:

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    initialization-mode: always

  jpa:
    database-platform: org.hibernate.dialect.H2Dialoect
    hibernate:
      ddl-auto: create-drop
    properties:
      hiberanete:
        format_sql: true
        show_sql: true

logging:
  level:
    com.example: DEBUG